---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tazblog-db
spec:
  template:
    metadata:
      labels:
        app: tazblog-db
    spec:
      containers:
        - image: eu.gcr.io/composite-watch-759/tazblog-haskell:f33723a
          name: tazblog-db
          command: ["tazblog-db"]
          volumeMounts:
            - name: tazblog-state
              mountPath: /var/tazblog
      volumes:
        - name: tazblog-state
          gcePersistentDisk:
            pdName: tazblog-state
            fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: tazblog-db
  labels:
    app: tazblog-db
spec:
  selector:
    app: tazblog-db
  ports:
    - port: 8070
      name: tazblog-db
