apiVersion: v1
kind: ReplicationController
metadata:
  name: tazblog-5.1.3
spec:
  replicas: 2
  selector:
    app: tazblog
    version: v5.1.3
  template:
    metadata:
      labels:
        app: tazblog
        version: v5.1.3
    spec:
      containers:
        - image: tazjin/tazblog-haskell:master
          imagePullPolicy: Always
          name: tazblog
          command: ["tazblog", "--dbHost", "tazblog-db.default.svc.cluster.local"]
          ports:
            - containerPort: 8000
        - image: tazjin/varnish
          imagePullPolicy: Always
          name: tazblog-varnish
          ports:
            - containerPort: 6081
            - containerPort: 6082
        - image: tazjin/hitch:master
          imagePullPolicy: Always
          name: tazblog-hitch
          command: ["hitch", "--backend=[127.0.0.1]:6083", "--write-proxy", "--user=hitch", "/etc/hitch/ssl/tazblog-tls"]
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tazblog-tls
              readOnly: true
              mountPath: /etc/hitch/ssl
          resources:
            requests:
              memory: "1024Mi"
      volumes:
        - name: tazblog-tls
          secret:
            secretName: tazblog-tls
