[package]
name = "journaldriver"
version = "0.1.0"
authors = ["Vincent Ambo <mail@tazj.in>"]

[dependencies]
libc = "0.2"
failure = "0.1"
systemd = "0.3"
log = "0.4"
env_logger = "0.5"

[build-dependencies]
pkg-config = "0.3"
