[package]
name = "crimp"
version = "0.1.0"
authors = ["Vincent Ambo <mail@tazj.in>"]

[features]
default = [ "json" ]
json = [ "serde", "serde_json"]

[dependencies]
curl = "0.4"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
