[package]
name = "journaldriver"
version = "0.1.0"
authors = ["Vincent Ambo <mail@tazj.in>"]

[dependencies]
libc = "0.2"
failure = "0.1"
systemd = "0.3"
log = "0.4"
env_logger = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = "0.8"
hyper = "0.11" # whatever reqwest drags in
lazy_static = "1.0"

[build-dependencies]
pkg-config = "0.3"
