apiVersion: v1
kind: ReplicationController
metadata:
  name: quassel
spec:
  replicas: 1
  selector:
    app: quassel
  template:
    metadata:
      labels:
        app: quassel
    spec:
      containers:
        - image: eu.gcr.io/composite-watch-759/quassel
          imagePullPolicy: Always
          name: quassel
          ports:
            - containerPort: 4242
          volumeMounts:
            - name: quassel-storage
              mountPath: /var/lib/quassel
      volumes:
        - name: quassel-storage
          gcePersistentDisk:
            pdName: quassel-storage
            fsType: ext4
