---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: nixery.local/shell/web.homepage:{{ gitHEAD }}
        env:
          - name: CONTAINER_SETUP
            value: "true"
        command: [ "homepage" ]
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: NodePort
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
