# Kontemplate configuration for the primary GKE cluster in the project
# 'tazjins-infrastructure'.
---
context: gke_tazjins-infrastructure_europe-north1_tazjin-cluster
include:
  # SSL certificates (provisioned by Google)
  - name: tazj-in-cert
    path: https-cert
    values:
      domain: tazj.in
  - name: www-tazj-in-cert
    path: https-cert
    values:
      domain: www.tazj.in
  - name: git-tazj-in-cert
    path: https-cert
    values:
      domain: git.tazj.in
  - name: oslo-pub-cert
    path: https-cert
    values:
      domain: oslo.pub

  # Services
  - name: nixery
    values:
      port: 8080
      version: xkm36vrbcnzxdccybzdrx4qzfcfqfrhg
      bucket: tazjins-data
      account: nixery@tazjins-infrastructure.iam.gserviceaccount.com
      repo: ssh://tazjin@gmail.com@source.developers.google.com:2022/p/tazjins-infrastructure/r/depot
      popularity: 'popularity-19.09.891.80b42e630b2.json'
  - name: tazblog
  - name: https-lb
  - name: nginx
    values:
      version: 52fabe4423095f12f67be1c7dbf88b801c1bb521
