# This is a child quinistry, running via an image served off the parent.
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: quinistry-gen2
  labels:
    k8s-app: quinistry
    quinistry/role: child
    quinistry/generation: '2'
spec:
  template:
    metadata:
      labels:
        k8s-app: quinistry
        quinistry/role: child
        quinistry/generation: '2'
    spec:
      containers:
        - name: quinistry
          # Bootstrap via Docker Hub (or any other registry)
          image: localhost:5000/quinistry
          ports:
            - name: registry
              containerPort: 8080
              # Incremented hostPort, 
              hostPort: 5001
