# This is a bootstrapped Quinistry DaemonSet. The initial image
# comes from Docker Hub
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: quinistry
  labels:
    k8s-app: quinistry
    quinistry/role: parent
    quinistry/generation: '1'
spec:
  template:
    metadata:
      labels:
        k8s-app: quinistry
        quinistry/role: parent
        quinistry/generation: '1'
    spec:
      containers:
        - name: quinistry
          # Bootstrap via Docker Hub (or any other registry)
          image: tazjin/quinistry
          ports:
            - name: registry
              containerPort: 8080
              hostPort: 5000
