---
apiVersion: v1
kind: Service
metadata:
  name: bitlbee
  labels:
    app: bitlbee
spec:
  type: LoadBalancer
  selector:
    app: bitlbee
  ports:
    - port: 6697
      targetPort: 6697
      name: irc-tls
