---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 104.155.119.229
  selector:
    lb-target: nginx
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 22
      name: ssh
    - port: 4242
      name: quassel
