---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    acme/certificate: '["tazj.in", "www.tazj.in", "ip.tazj.in", "git.tazj.in"]'
    acme/secretName: tazj.in-tls
spec:
  type: LoadBalancer
  loadBalancerIP: 104.155.119.229
  selector:
    app: nginx
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 22
      name: ssh
    - port: 4242
      name: quassel
