---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-v3
  labels:
    app: nginx
    version: 1.9.11
    spec: v3
spec:
  replicas: 2
  selector:
    app: nginx
    rcv: v3
  template:
    metadata:
      labels:
        app: nginx
        lb-target: nginx
        rcv: v3
    spec:
      containers:
        - image: nginx:1.9.11
          name: nginx
          volumeMounts:
            - name: tazj-in-tls
              mountPath: /etc/nginx/ssl/tazj.in
            - name: nginx-dhparam
              mountPath: /etc/nginx/ssl/dhparam
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-logs
              mountPath: /var/log/nginx
          ports:
            - containerPort: 80
            - containerPort: 443
        - image: reactivehub/google-fluentd-catch-all
          name: google-log-agent
          volumeMounts:
            - name: nginx-logs
              mountPath: /var/log/nginx
      volumes:
        - name: tazj-in-tls
          secret:
            secretName: tazj-in-tls
        - name: nginx-dhparam
          secret:
            secretName: nginx-dhparam
        - name: nginx-config
          secret:
            secretName: nginx-config
        - name: nginx-logs
          emptyDir: {}
