[package]
name = "posix_mq"
version = "0.9.0"
authors = ["Vincent Ambo <mail@tazj.in>"]
description = "(Higher-level) Rust bindings to POSIX message queues"
license = "MIT"
repository = "https://git.tazj.in/tree/ops/posix_mq.rs"

[dependencies]
nix = "0.16"
libc = "0.2"
