[package]
name = "posix_mq"
version = "0.1.3"
authors = ["Vincent Ambo <vincent@aprila.no>"]
description = "(Higher-level) Rust bindings to POSIX message queues"
license = "MIT"
repository = "https://github.com/aprilabank/posix_mq.rs"

[dependencies]
nix = "0.9"
libc = "0.2"
