apiVersion: v1
kind: ReplicationController
metadata:
  name: gogs
spec:
  replicas: 1
  selector:
    app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
        - image: gogs/gogs
          imagePullPolicy: Always
          name: gogs
          ports:
            - containerPort: 22
            - containerPort: 3000
          volumeMounts:
            - name: gogs-storage
              mountPath: /data
      volumes:
        - name: gogs-storage
          gcePersistentDisk:
            pdName: gogs-storage
            fsType: ext4
