apiVersion: v1
kind: ReplicationController
metadata:
  name: gogs
spec:
  replicas: 1
  selector:
    app: gogs
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
        - image: gogs/gogs
          imagePullPolicy: Always
          name: gogs
          ports:
            - containerPort: 22
            - containerPort: 3000
          volumeMounts:
            - name: gogs-storage
              mountPath: /data
        - image: nginx:1.9
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: gogs-tls
              mountPath: /etc/nginx/ssl
            - name: gogs-nginx
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: gogs-storage
          gcePersistentDisk:
            pdName: gogs-storage
            fsType: ext4
        - name: gogs-tls
          secret:
            secretName: gogs-tls
        - name: gogs-nginx
          secret:
            secretName: gogs-nginx
