apiVersion: v1
kind: Service
metadata:
  name: gogs
  labels:
    app: gogs
spec:
  type: LoadBalancer
  selector:
    app: gogs
  ports:
    - port: 22
      targetPort: 22
      name: git-ssh
    - port: 443
      targetPort: 443
      name: gogs-https
    - port: 80
      targetPort: 80
      name: gogs-http
