apiVersion: v1
kind: Service
metadata:
  name: gogs-priv
  labels:
    app: gogs
spec:
  selector:
    app: gogs
  ports:
    - port: 3000
      name: gogs-http-internal
    - port: 22
      name: gogs-ssh-internal
